### ISSUE TITLE
Transferring only necessary data instead of allusers/allcourses

### ISSUE THREAD

**Issue by SteffenPegenau** [eLearning-TUDarmstadt/moodle-tool_supporter#1]
https://github.com/SteffenPegenau/moodle-analyst/issues/74

**Comment by KlaraSaary** [comment]
Transferring all users and courses leads to a better performance on a normal work day, but we will only load important user and course information at first and special one later

**Comment by Nullmann** [comment]
We decided to all courses and users but only a few of them: 
id, fullname, course category, parent course category and visibility for courses
id, username, firstname, lastname, email for users
