### ISSUE TITLE
Invalid response value detected

### ISSUE THREAD

**Issue by MoodleMood** [eLearning-TUDarmstadt/moodle-tool_supporter#107]
Moodle release: **3.7.2**

Plugin Release: **v1.02**

Plugin version: **2019102304**

Accessing the plugin via 

**Administration** > R**eports** > **Supporter**

or the link directly 

**https://moodle.website.ab.xy/admin/tool/supporter/index.php**

returns the following error:

**Invalid response value detected**

![Supporter - error](https://user-images.githubusercontent.com/54653712/69922706-a2490100-1503-11ea-9302-f7a9a5e2f98a.jpg)

Plugin settings:

![Supporter - settings](https://user-images.githubusercontent.com/54653712/69922691-7463bc80-1503-11ea-9166-88b6c6d3274a.jpg)

Note 1:
Tried to play with the settings but the plugin returns the same results.

Note 2:
Operating another website with the same Moodle release, PHP engine, and identical settings of the plugin and the plugin seems to be working fine - what to check or/and compare?

Relevant screenshots attached.

Thanks in advance, any help would be appreciated.

**Comment by Nullmann** [comment]
Hello, this is weird. The users cannot be loaded and the error message suggests that there is a problem with the external function, probably the return data of get_users function here: https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/blob/master/classes/external.php#L498

Can you turn on debugging mode in the developer settings and/or look into your php error logs file to find out the specific error with the data structure.

**Comment by ksteitz** [comment]
closed due to no answer since 2019

**Comment by ksteitz** [comment]
closed due to no answer since 2019
