### ISSUE TITLE
Strings hardcoded to English

### ISSUE THREAD

**Issue by dinism** [eLearning-TUDarmstadt/moodle-tool_supporter#108]
I'm a PT-PT Moodle translator. Can this strings be translated? These strings are in different pages.
![imagem](https://user-images.githubusercontent.com/14828021/81014067-1b9ea400-8e54-11ea-9d16-56f1245eaad7.png)

Thanks a lot.

**Comment by ksteitz** [comment]
check if strings may/shall be used by AMOS; risk: display doesn´t fit (e.g. overlap) due to length in some languages, e.g. german

**Comment by dinism** [comment]
YES they can be used.

**Comment by ksteitz** [comment]
> YES they can be used.

Thanks for your quick reply. I have checked amos now, finding 29 strings. 
So this issue is solved now?

**Comment by my-curiosity** [comment]
Text for semester and department fields can be changed in supporter configuration. Search and refresh text use lang strings now (fixed in 4_dev branch).
If I understand correctly, the issue is solved.
