### ISSUE TITLE
Adaptable Theme Issues

### ISSUE THREAD

**Issue by demontech** [eLearning-TUDarmstadt/moodle-tool_supporter#109]
I just installed in on the Adaptable theme on M3.6 - php 7.0 and MySQL 5.7 and this is how it looks:

![image](https://user-images.githubusercontent.com/8148238/106853582-cdcafc80-666e-11eb-9bab-8f9fa84ada7c.png)

![image](https://user-images.githubusercontent.com/8148238/106853648-e5a28080-666e-11eb-9627-301f3693788f.png)

![image](https://user-images.githubusercontent.com/8148238/106853705-fa7f1400-666e-11eb-94f7-c83151ff275b.png)

![image](https://user-images.githubusercontent.com/8148238/106853893-45992700-666f-11eb-9fdd-5c64c20de98d.png)

![image](https://user-images.githubusercontent.com/8148238/106961703-d6651680-66f2-11eb-9332-4f2e7e741f24.png)

Thank you for this great tool !!

Mark

**Comment by my-curiosity** [comment]
Hi, Moodle 3.6 is not currently supported and I could not reproduce the issue in Moodle 4, which is our target at the moment. If the problem is still present for you in 3.10 or newer, feel free to reopen this.
