### ISSUE TITLE
"nopermissions" modal using Level 1 Support (read-only)

### ISSUE THREAD

**Issue by ksteitz** [eLearning-TUDarmstadt/moodle-tool_supporter#110]
Using Level 1 Support (read-only) with capablities 
    moodle/site:viewparticipants
    moodle/user:viewdetails (requires site:viewparticipants)
    moodle/course:viewhiddencourses
    moodle/course:view (requires course:viewhiddencourses)

a modal "nopermissions" opens by clicking a course in the left-hand-side "courses" list, if a user is selected right-hand-side below "Users", saying: 
"nopermissions
Sorry, but you do not currently have permissions to do that (Enrol users)."

This is annoying, particularly it is obvious that the read-only role owns no capabilties for enroling users.

**Comment by ksteitz** [comment]
![grafik](https://user-images.githubusercontent.com/1639438/176903665-a89a010a-6077-4ee7-8eca-59720eaf1d38.png)

**Comment by my-curiosity** [comment]
Should be fixed in moodle_4_dev branch, message is now shown only when level 1 support clicks on the enrol button.
