### ISSUE TITLE
Clicking on a course shows additional information

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#16]
- Course Information
- Who is enrolled with which role

**Comment by thomaswilker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tool Supporter](https://trello.com/c/YwfR2reL/35-tool-supporter)

**Comment by Nullmann** [comment]
Was realized in 9455893cd8fd44bad4d6e0d9fabaab59743f87ab

**Comment by Nullmann** [comment]
ToDo: Display users, activities

Clean error: https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/issues/32

**Comment by KlaraSaary** [comment]
Only filterin is missing -> Issue #30
