### ISSUE TITLE
Implement better sort algorithm in table_sort.js

### ISSUE THREAD

**Issue by KlaraSaary** [eLearning-TUDarmstadt/moodle-tool_supporter#42]
Currently the sorting algorithm (bubbleSort) for sorting tables has a bad performance. A better algorithm  has to be implemented. Maybe a plugin has to be used. Interesting is also the flexible_table from moodle. But it is badly documented

**Comment by KlaraSaary** [comment]
Using jquery-plugin DataTable solves the problem, but the tab-tables in course-details don't work as DataTable yet

**Comment by Nullmann** [comment]
Add Visuals which is sorted and that the tables are sortable

**Comment by KlaraSaary** [comment]
implementing DataTables for all tables solves the problem
