### ISSUE TITLE
Find out how to use glyphicons (bootstrap) or icons (fontawesome)

### ISSUE THREAD

**Issue by KlaraSaary** [eLearning-TUDarmstadt/moodle-tool_supporter#45]

**Comment by Nullmann** [comment]
Is already a part of https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/issues/5

Do not use Glyphicons. Use moodle-integrated pix instead:
https://docs.moodle.org/dev/Templates#.7B.7B.23_pix_.7D.7D
