### ISSUE TITLE
Missing strings: Role names when displaying course details

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#66]
Arose from #14 

manager, editingteacher, teacher, student, etc

there is currently no easy way to fix this

**Comment by KlaraSaary** [comment]
@Nullmann : I could not recreate the problem. Could you explicate the issue?

**Comment by Nullmann** [comment]
When changing the language to - for example - french, these strings are not translated:

![wrong role strings](https://cloud.githubusercontent.com/assets/15816473/25659782/9d0dbee2-3009-11e7-98ac-a9d49a961b9f.png)

**Comment by Nullmann** [comment]
Working fine for courses, but is not done for users. 

![rollen](https://user-images.githubusercontent.com/15816473/27634135-67b112e2-5c02-11e7-91dd-09305f47c530.jpg)
