### ISSUE TITLE
[mdl-dev] big amounts of data are not supported 

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#67]
trying to open the plugin takes ages and leads the to the browser to not respond for several minutes.

tested on newly created, TU intern, mdl-dev with duplicated Database from TU intern Beta-Server:

CAUTION! when using this link. May cause Browser to go down.
http://mdl-db-dev.hrz.tu-darmstadt.de/admin/tool/supporter/
(Access only from within our network and login with local support account, as usual)

git was cloned on 3rd of May 2017

**Comment by Nullmann** [comment]
Maybe compressing the code can create a more stable version.

It can be done by building with bower / grunt

**Comment by Nullmann** [comment]
Displaying the data only after the tables are loaded is a good idea - see commits https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/commit/077480f6fb4cd8a92e95e16a569cfdfa7d22d65c and https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/commit/a03225a9861235d41d0806a3b358ab7e2fe0d12c

But this does not yet work on mdl-dev because the rendering of the datatables and css and such is not working.

**Comment by KlaraSaary** [comment]
The loading time seems now the same as the moodleAnalyst loading time
