### ISSUE TITLE
[mdl-dev] tables are not displayed correctly- one on top of the other

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#69]
First the courses and then the users

tested on newly created, TU intern, mdl-dev with duplicated Database from TU intern Beta-Server:

CAUTION! when using this link. May cause Browser to go down.
http://mdl-db-dev.hrz.tu-darmstadt.de/admin/tool/supporter/
(Access only from within our network and login with local support account, as usual)

git was cloned on 3rd of May 2017

**Comment by Nullmann** [comment]
Maybe disabling the tudarmstadt-theme can helpe?

**Comment by Nullmann** [comment]
Using the "clean"-theme on mdl-dev sadly does not work either.

**Comment by KlaraSaary** [comment]
Can't seethe issue anymore
