### ISSUE TITLE
After changing table page disables clicking on users/courses

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#70]
Steps to reproduce:
- Add enough users / courses to have a 2nd page
- Click on 2nd page
- Try to click on a user / course, it does not work

Problem is probably caused by changing the table and thus jquery does not work anymore.

**Comment by KlaraSaary** [comment]
Could not recreate it. Maybe one of the last commits fixed it. Please try again and if it fixed close the issue

**Comment by Nullmann** [comment]
It is not yet fixed. After changing a page I cannot click on a user.

**Comment by Nullmann** [comment]
Changed

**Comment by Nullmann** [comment]
Changed the jquery according to the datatables-example here:
https://datatables.net/examples/advanced_init/events_live.html
Seems to have fixed it.

@KlaraSaary pleas confirm that it is working for you too and close the issue.

**Comment by Nullmann** [comment]
I'll just close it, then. The bug only occured for me anyway.
