### ISSUE TITLE
[styling] Table-Headers are not above columns

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#78]
They are to the most-left, see

![headers](https://user-images.githubusercontent.com/15816473/27863610-3ade8a2c-618b-11e7-89bb-e1b0726b327e.jpg)

**Comment by KlaraSaary** [comment]
In the momemt you change the size after the first time loading the page everthing falls into the right place.

**Comment by Nullmann** [comment]
Seems to be solved atm. Closing it until it reoccurs.
