### ISSUE TITLE
capbility "supporter:view" was added but throws issues

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#79]
We wanted to not add additional capabilities to the tool, see https://github.com/eLearning-TUDarmstadt/moodle-tool_supporter/issues/12

Also, it throws errors anyways.
Error Message in Moodle:

![screenshot](https://user-images.githubusercontent.com/15816473/30372215-66d8526a-987d-11e7-8c88-009d4e3b7536.jpg)

Occurences in Code:

![screenshot](https://user-images.githubusercontent.com/15816473/30372239-77384d22-987d-11e7-8ea1-e1199e815d4d.jpg)

**Comment by SteffenPegenau** [comment]
Is the capability in the DB as well?

Am 13.09.2017 12:18 schrieb "Benedikt Schneider" <notifications@github.com>:

**Comment by Nullmann** [comment]
This was since commented out because we resorted to moodle-capabilites.
