### ISSUE TITLE
Same label for different settings

### ISSUE THREAD

**Issue by mudrd8mz** [eLearning-TUDarmstadt/moodle-tool_supporter#94]
The label "Ordering of the first ID-Column" is used for multiple settings such as course_table_order, user_table_order, course_details_order etc.

That is not optimal as these fields can sometimes be displayed on their own without the context of the surrounding fields (e.g. when searching the administration for a keyword). As a general accessibility recommendation, the labels should uniquely identify the field.

**Comment by Nullmann** [comment]
Todo when the AMOS-submission for german language strings is accepted: https://lang.moodle.org/local/amos/contrib.php?id=29370

I do not want to confuse someone by changing the language strings while they are not even accepted yet.

**Comment by Nullmann** [comment]
As this issue only affects language strings and no critical code, I am closing this issue after adding separate language strings for each setting.
