### ISSUE TITLE
Clicking the unenrol gives error

### ISSUE THREAD

**Issue by mudrd8mz** [eLearning-TUDarmstadt/moodle-tool_supporter#95]
It seems that that template `user_detail.mustache` does not have the `wwwroot` valua available. When the Moodle is installed in a subdirectory of a server, and the user clicks "Unenrol" icon, they are redirected to an invalid URL without the path.

**Comment by Nullmann** [comment]
This is a simple fix. But because I do not know why this even worked until now I cannot test this properly and would like your help @mudrd8mz

**Comment by Nullmann** [comment]
I now understood your issue. When the moodle URL is something like <www.url.com/education/moodle>, it broke any links in the user_detail and course_detail.

My earlier commit actually did not do anything as it only passed the wwwroot variable when the site was first loaded but not when the actual data was loaded for the *_detail pages. 

As I could test and fix this now I also closed the issue.

Thank you so much for reporting this - in both our test and live environments we would have never found this issue!

**Comment by mudrd8mz** [comment]
Thanks!
