### ISSUE TITLE
Course category referred to as "Semesters" and "Departments"

### ISSUE THREAD

**Issue by mudrd8mz** [eLearning-TUDarmstadt/moodle-tool_supporter#96]
The plugin seems to interpret the first level of course categories as "semesters" and the second level as "departments". I can understand that is how your particular institution / university uses the course categories to organise the courses and so this way fits your need perfectly.

However, other institutions might have different setups. In which case, the hard-coded terminology will be quite confusing.

**Comment by Nullmann** [comment]
Hello @mudrd8mz, thank you for the incoming feedback!

Did you see the settings menu in which you can change the naming of the headers? It is accessible via the cog in the navbar or by going to Server Administration -> Reports -> Supporter Settings

Or did you mean that it is named this way in the code (which it may very well be, but I am unsure of at the moment)?

**Comment by mudrd8mz** [comment]
Oh yes! I see it now. Sorry. I saw that option but I did not fully realize that I should actually use it for this. All good then - not a bug but actually a useful and well designed feature :-)
