### ISSUE TITLE
settings.php inline comment not fully right

### ISSUE THREAD

**Issue by mudrd8mz** [eLearning-TUDarmstadt/moodle-tool_supporter#97]
In settings.php, there is an inline comment
```
    // These are currently stored in the "mdl_config"-table.
```
However, that does not seem to be right any more. The plugin now correctly stores the config settings in the `config_plugins` table. I believe this inline comment is a relic from an older development stage as the commit 5c8d91072427aea64bbdb3df980fa4c026359b96 fixed the settings storage.

**Comment by Nullmann** [comment]
As this is just a fix to a comment I just close the issue as solved.
